package ewision.sahan.components.action_panels;

import ewision.sahan.components.action_button.ActionButtonEvent;
import ewision.sahan.utils.ImageScaler;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JTable;

public class ActionButtonPanel3 extends javax.swing.JPanel {

    private JTable table;
    //private HashMap<String, ActionButtonEvent> eventMap;

    /**
     * Creates new form ActionButtonPanel
     */
    //public ActionButtonPanel3(JTable table, ActionButtonEvent editEvent, ActionButtonEvent viewEvent, ActionButtonEvent deleteEvent ) {
    public ActionButtonPanel3(JTable table, HashMap eventMap) {
        initComponents();
        //this.eventMap = eventMap;
        edit.setEvent((ActionButtonEvent) eventMap.get("edit"));
        delete.setEvent((ActionButtonEvent) eventMap.get("delete"));
        view.setEvent((ActionButtonEvent) eventMap.get("view"));
        //edit.setEvent(editEvent);
        //delete.setEvent(deleteEvent);
        //view.setEvent(viewEvent);
        renderButtons();
        this.table = table;
    }

    public ActionButtonPanel3(JTable table) {
        initComponents();
        renderButtons();
        this.table = table;
    }

    private void renderButtons() {
        ImageScaler scaler = new ImageScaler();
        delete.setIcon(scaler.getSvgIcon("/delete.svg", 30));
        edit.setIcon(scaler.getSvgIcon("/edit.svg", 30));
        view.setIcon(scaler.getSvgIcon("/view.svg", 30));
    }

    public void initEvent(int row) {
        edit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //onEdit(row);
                edit.getEvent().run(row);
            }
        });
        delete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //onDelete(row);
                if (table.isEditing()) {
                    table.getCellEditor().stopCellEditing();
                }
                delete.getEvent().run(row);
            }
        });
        view.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //onView(row);
                view.getEvent().run(row);
            }
        });
    }

//    private void onView(int row) {
//        view.getEvent().run(row);
//        //System.out.println("View: " + row);
//    }
//
//    private void onEdit(int row) {
//        edit.getEvent().run(row);
//        //System.out.println("Edit: " + row);
//    }
//
//    private void onDelete(int row) {
//        if (table.isEditing()) {
//            table.getCellEditor().stopCellEditing();
//            //System.out.println(String.valueOf(table.getValueAt(row, 3))); //data access
//        }
//        delete.getEvent().run(row);
//        //System.out.println("Delete: " + row);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view = new ewision.sahan.components.action_button.ActionButton();
        edit = new ewision.sahan.components.action_button.ActionButton();
        delete = new ewision.sahan.components.action_button.ActionButton();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ewision.sahan.components.action_button.ActionButton delete;
    private ewision.sahan.components.action_button.ActionButton edit;
    private ewision.sahan.components.action_button.ActionButton view;
    // End of variables declaration//GEN-END:variables
}
