package ewision.sahan.components.action_panels;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import ewision.sahan.components.action_button.ActionButtonEvent;
import ewision.sahan.model.Constants;
import ewision.sahan.utils.ImageScaler;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JTable;

public class ActionButtonPanel6 extends javax.swing.JPanel {

    private JTable table;

    /**
     * Creates new form ActionButtonPanel
     */
    public ActionButtonPanel6(JTable table) {
        initComponents();
        renderButtons();
        this.table = table;
    }

    public ActionButtonPanel6(JTable table, HashMap eventMap) {
        initComponents();
        init(eventMap);
        this.table = table;
    }

        private void init(HashMap eventMap) {
        renderButtons();
        edit.setEvent((ActionButtonEvent) eventMap.get("edit"));
        //setBackground(Constants.TRANSPARENT);
    }

    
    private void renderButtons() {
        //edit.setIcon(new ImageScaler().getSvgIcon("/edit.svg", 30));
        //edit.setIcon(new FlatSVGIcon(getClass().getResource("/ewision/sahan/icon/svg/edit.svg").getPath(), 30, 30));
        edit.setIcon(new FlatSVGIcon(getClass().getResource("/ewision/sahan/icon/svg/edit.svg")));
    }

    public void initEvent(int row) {
        edit.addActionListener((ActionEvent evt) -> {
            //onDelete(row);
            edit.getEvent().run(row);
        });
    }

//    private void onDelete(int row) {
//        if (table.isEditing()) {
//            table.getCellEditor().stopCellEditing();
//            System.out.println(String.valueOf(table.getValueAt(row, 3)));
//        }
//        delete.getEvent().run(row);
//        //System.out.println("Delete: " + row);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit = new ewision.sahan.components.action_button.ActionButton();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ewision.sahan.components.action_button.ActionButton edit;
    // End of variables declaration//GEN-END:variables
}
