package ewision.sahan.components.action_panels;

import ewision.sahan.components.action_button.ActionButtonEvent;
import ewision.sahan.utils.ImageScaler;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JTable;

public class ActionButtonPanel1 extends javax.swing.JPanel {

    private JTable table;

    /**
     * Creates new form ActionButtonPanel
     */
    public ActionButtonPanel1(JTable table, HashMap eventMap) {
        initComponents();
        actionMenu.setEvent((ActionButtonEvent) eventMap.get("action"));
        renderButtons();
        this.table = table;
    }

    public ActionButtonPanel1(JTable table) {
        initComponents();
        renderButtons();
        this.table = table;
    }

    private void renderButtons() {
        actionMenu.setIcon(new ImageScaler().getSvgIcon("/action.svg", 30));
    }

    public void initEvent(int row) {
        actionMenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //onActionMenu(row);
                actionMenu.getEvent().run(row);
            }
        });
    }

//    private void onActionMenu(int row) {
//        actionMenu.getEvent().run(row);
//        //System.out.println("View: " + row);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionMenu = new ewision.sahan.components.action_button.ActionButton();

        actionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ewision.sahan.components.action_button.ActionButton actionMenu;
    // End of variables declaration//GEN-END:variables
}
