package ewision.sahan.payment;

import ewision.sahan.purchase.*;
import com.formdev.flatlaf.FlatClientProperties;
import ewision.sahan.application.Application;
import ewision.sahan.loggers.CommonLogger;
import ewision.sahan.loggers.DatabaseLogger;
import ewision.sahan.model.MySQL;
import ewision.sahan.model.Product;
import ewision.sahan.model.Stock;
import ewision.sahan.utils.SQLDateFormatter;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JTextField;

/**
 *
 * @author ksoff
 */
public class AddPayment extends javax.swing.JPanel {

    private CreatePurchase1 createPurchase;
    private Product product;
    private Stock stock;
    private String stock_id;
    private String id;

    /**
     * Creates new form SelectStock
     */
    public AddPayment() {
        initComponents();
        init();
    }

    public AddPayment(CreatePurchase1 createPurchase, String id, String refference) {
        initComponents();
        this.createPurchase = createPurchase;
        idLabel.setText(id);
        refferenceField.setText(refference);
        init();
    }

    public AddPayment(CreatePurchase1 createPurchase, Product product) {
        initComponents();
        this.createPurchase = createPurchase;
        this.product = product;
        setUIData();
        init();
    }

    private void setUIData() {
        idLabel.setText(String.valueOf(product.getId()));
        refferenceField.setText(product.getName());
    }

    private void init() {
        styleComponents();
        initData();
        toggleFields(false);
        reset();
    }

    private void initData() {
        jDateChooser1.setDate(new Date());
    }

    private void toggleFields(boolean enable) {
        paymentField.setEnabled(enable);
        jDateChooser1.setEnabled(enable);
        receiveField.setEnabled(false);
        changeField.setEnabled(false);
        refferenceField.setEnabled(false);
    }

    private void reset() {
        toggleFields(true);
        paymentField.setText("0.00");
        receiveField.setText("0.00");
        changeField.setText("0.00");
        paymentMethodComboBox.setSelectedIndex(0);
        initData();
    }

    private void styleComponents() {
        addPanel.putClientProperty(FlatClientProperties.STYLE, "arc:20;"
                + "background:$SubPanel.background");
        addButton.putClientProperty(FlatClientProperties.STYLE, "arc:20;");
        JTextField[] fields = {changeField, paymentField, receiveField, refferenceField};
        for (JTextField field : fields) {
            field.putClientProperty(FlatClientProperties.STYLE, "arc:15");
        }
    }

    private void calculate() {
        double receive = 0;
        try {
            receive = Double.valueOf(receiveField.getText());
        } catch (NumberFormatException | NullPointerException e) {
            CommonLogger.logger.log(Level.SEVERE, "Exception in " + getClass().getName() + " calculate receive: " + e.getMessage(), e.getMessage());
        }

        double payment = 0.00;
        try {
            payment = Double.parseDouble(String.valueOf(paymentField.getText()));
        } catch (NumberFormatException | NullPointerException e) {
            CommonLogger.logger.log(Level.SEVERE, "Exception in " + getClass().getName() + " calculate payment: " + e.getMessage(), e.getMessage());
        }

        double change = 0.00;
        change = receive - payment;

        //subTotalLabel.setText(String.valueOf(((stock == null) ? 0 : stock.getStock_price() * quantity) - discount - tax));
        changeField.setText(createPurchase.getCurrency() + change);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        receiveField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        paymentField = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        refferenceField = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        changeField = new javax.swing.JFormattedTextField();
        paymentMethodComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteText = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));

        addPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabel2.setText("Change :");

        jLabel5.setText("Date");

        receiveField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        receiveField.setText("0.00");
        receiveField.setNextFocusableComponent(paymentField);
        receiveField.setPreferredSize(new java.awt.Dimension(277, 33));
        receiveField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                receiveFieldFocusGained(evt);
            }
        });
        receiveField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                receiveFieldKeyReleased(evt);
            }
        });

        jLabel7.setText("Received Amount");

        jLabel10.setText("Refference");

        jLabel11.setText("Paying Amount");

        paymentField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        paymentField.setText("0.00");
        paymentField.setNextFocusableComponent(paymentField);
        paymentField.setPreferredSize(new java.awt.Dimension(277, 33));
        paymentField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentFieldFocusGained(evt);
            }
        });
        paymentField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paymentFieldKeyReleased(evt);
            }
        });

        jLabel12.setText("Payement Choice");

        refferenceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                refferenceFieldFocusGained(evt);
            }
        });

        changeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        changeField.setText("0.00");
        changeField.setNextFocusableComponent(paymentField);
        changeField.setPreferredSize(new java.awt.Dimension(277, 33));
        changeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                changeFieldFocusGained(evt);
            }
        });
        changeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                changeFieldKeyReleased(evt);
            }
        });

        paymentMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit Card", "Cheque" }));

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiveField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addComponent(changeField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(refferenceField)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(paymentMethodComboBox, 0, 155, Short.MAX_VALUE))
                .addContainerGap())
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refferenceField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiveField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentMethodComboBox))
                .addGap(7, 7, 7))
        );

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel8.setText("Make Payment");

        idLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLabel.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addButton.setText("Add");
        addButton.setNextFocusableComponent(receiveField);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        noteText.setColumns(20);
        noteText.setRows(5);
        jScrollPane2.setViewportView(noteText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPanel, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // Add payment
        double total = 0;
        try {
            total = Double.valueOf(receiveField.getText());
        } catch (NumberFormatException | NullPointerException e) {
            CommonLogger.logger.log(Level.SEVERE, "Exception in " + getClass().getName() + " calculate receive: " + e.getMessage(), e.getMessage());
        }

        double payment = 0.00;
        try {
            payment = Double.parseDouble(String.valueOf(paymentField.getText()));
        } catch (NumberFormatException | NullPointerException e) {
            CommonLogger.logger.log(Level.SEVERE, "Exception in " + getClass().getName() + " calculate payment: " + e.getMessage(), e.getMessage());
        }

        double balance = 0.00;
        balance = total - payment;
        
        SQLDateFormatter dateFormatter = new SQLDateFormatter();

        String currentDate = dateFormatter.getStringDate(new Date());
        String currentDateTime = dateFormatter.getStringDateTime(new Date());

        long mil = System.currentTimeMillis();
        String ref = String.valueOf((int) mil).substring(3);

        String payQuery = "INSERT INTO `payment_sales` (`user_id`, `date`, `Ref`, `sale_id`, `montant`, `change`, `Reglement`, `notes`, `created_at`, `updated_at`, `deleted_at`) VALUES ('" + Application.getUser().getStringId() + "', '" + currentDate + "', '" + ref + "', '" + this.id + "', '" + total + "', '" + balance + "', '" + payment + "', NULL, '" + currentDateTime + "', NULL, NULL)";
        try {
            MySQL.execute(payQuery);
        } catch (SQLException e) {
            DatabaseLogger.logger.log(Level.SEVERE, "SQLException in " + getClass().getName() + " Sale Submit Sale payment: " + e.getMessage(), e.getMessage());
        }

//        if (createPurchase != null) {
//            String code = refferenceField.getText();
//            String currentQuantity = "0";
//            //String currentQuantity = quantity;
//            String price = changeField.getText();
//            String tax = paymentField.getText();
//            String discount = receiveField.getText();
//
//            Date exp = jDateChooser1.getDate();
//
//            if (code.isBlank()) {
//            } else if (price.isBlank() || price.equals("0.00")) {
//            } else if (discount.isBlank()) {
//            } else if (tax.isBlank()) {
//            } else {
//                if (stock == null) {
//                    stock = new Stock();
//                    stock.setProduct(product);
//                } else {
//                    currentQuantity = String.valueOf(stock.getStock_quantity());
//                    //currentQuantity = String.valueOf(stock.getStock_quantity() + Double.parseDouble(quantity));
//                }
//
//                stock.setStock_code(code);
//                stock.setStock_quantity(currentQuantity);
//
//                stock.setStock_discount(discount);
//                stock.setStock_price(price);
//                stock.setStock_tax(tax);
//
//                createPurchase.addProductToInvoice(stock);
//                reset();
//                createPurchase.closeModal();
//            }
//        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void receiveFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_receiveFieldFocusGained
        // Select on Focus
    }//GEN-LAST:event_receiveFieldFocusGained

    private void receiveFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiveFieldKeyReleased
        // Calculate on Value Change
    }//GEN-LAST:event_receiveFieldKeyReleased

    private void changeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_changeFieldFocusGained
        // Select on Focus
    }//GEN-LAST:event_changeFieldFocusGained

    private void changeFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_changeFieldKeyReleased
        // Calculate on Value Change
    }//GEN-LAST:event_changeFieldKeyReleased

    private void paymentFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentFieldFocusGained
        // Select on Focus
        paymentField.selectAll();
    }//GEN-LAST:event_paymentFieldFocusGained

    private void paymentFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentFieldKeyReleased
        // Calculate on Value Change
        String text = paymentField.getText();
        paymentField.setText(text.isBlank() ? "0.00" : text);
        if (!paymentField.getText().equals("0.00")) {
            calculate();
        }
    }//GEN-LAST:event_paymentFieldKeyReleased

    private void refferenceFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_refferenceFieldFocusGained
        // Select on Focus
    }//GEN-LAST:event_refferenceFieldFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JFormattedTextField changeField;
    private javax.swing.JLabel idLabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea noteText;
    private javax.swing.JFormattedTextField paymentField;
    private javax.swing.JComboBox<String> paymentMethodComboBox;
    private javax.swing.JFormattedTextField receiveField;
    private javax.swing.JTextField refferenceField;
    // End of variables declaration//GEN-END:variables
}
